- name: Install Nginx on webservers
  hosts: inception
  become: yes
  vars:
    docker_packages:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    user: admin
    project_dir: "/opt/app"

  roles:
    - docker
    - copy project configs
    - db
    - wordpress
    - phpmyadmin
    - nginx