- name: Install Nginx on webservers
  hosts: inception
  become: yes
  vars:
    user: ubuntu
    project_dir: "/opt/app"

  roles:
    - docker
    - copy project configs
    - db
    - wordpress
    - phpmyadmin
    - nginx